name: 'MrMat Conditional Release Action'
description: 'A GitHub action to perform a conditional project release the way I like it'
inputs:
    token:
        description: 'The token to use for authenticating to the GitHub API'
    version:
        description: 'The version to release'
        required: true
    title:
        description: 'The release title'
        required: true
runs:
    using: 'node16'
    main: 'dist/index.js'
